services:
  - type: web
    name: handy-backend
    env: node
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/CiscoPonce/Handy_1_10.git
    runtime: nodejs
    nodeVersion: 18.x
    rootDir: backend
    buildCommand: npm install && npm run build --verbose
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: true
    numInstances: 1
    publishPath: dist
